<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>0.6.5</Version>
    <InformationalVersion>$(Version)</InformationalVersion>
    <Authors>Antônio Abrantes</Authors>
    <Product>DesktopFences</Product>
    <NeutralLanguage>pt-BR</NeutralLanguage>
  </PropertyGroup>
</Project>
